version: '3.4'

services:
  fibonaccidb:
    container_name: fibonaccidb
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "SwN12345678"
      ACCEPT_EULA: "Y"

  fibonacci.restapi:
    container_name: fibonaccirestapi
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:ConnectionString=Server=fibonaccidb;Database=FibonacciDb;User Id=sa;Password=SwN12345678"            
    depends_on:
      - fibonaccidb            
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports:
      - "8002:80"

  img.fibo.front:
    container_name: imgfibofront
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
    depends_on:
      - fibonacci.restapi
    ports:
      - "8001:80"